name: Sync Fork with Upstream

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - master  # 只有推送到 `master` 分支时才触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/blackmatrix7/ios_rule_script.git

      - name: Fetch upstream changes
        run: |
          git fetch upstream

      - name: Merge upstream changes into master
        run: |
          git checkout master
          git merge upstream/master --strategy=recursive --strategy-option=theirs -m "Merge upstream changes"

      - name: Push changes to fork
        run: |
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Actions 自动提供的权限令牌
